### ISSUE TITLE
Issue with DI signal Run_Camera_Command

### ISSUE THREAD

**Issue by lucapi-eng** [kth-ros-pkg/yumi#38] opened 2019-04-22 08:51 UTC
Hi!

I am trying to do improvements in YuMi´s vision but I am having some issues with the parameter RUN_CAMERA_COMMAND. When I try to check the code I get the following error:
 
"14000-501654/RAPID/T_ROB_R/TCameraMain(200,19): Reference error(128): Reference to unknown entire data RUN_CAMERA_COMMAND."

While creating the DI signal, I would like to ask you some questions about fields I am not sure how should I fill them in. First, Should I assign it to device D652_10 just like the rest of Custom_DI signals or should I create a new device for it? Secondly, in the device mapping field should I write a number or it does not apply in this case? And finally what category should it have? Or it is not a necessary field?

I attach a screenshot so that you can see what fields I am talking about.

Thank you very much,
Luis

![Capture](https://user-images.githubusercontent.com/49858738/56491550-3b815500-64e9-11e9-8bf5-7c234ff20969.PNG)

**Comment by jontje** [comment] 2019-04-23 07:01
@luisrcadarso, the `RUN_CAMERA_COMMAND` was intended to be a _virtual IO-signal_, meaning that it is not connected to a physical device.

You can for example use this configuration:
* `Assigned to Device`: Can be left empty
* `Device mapping`: Can be left empty
* `Category`: Can be left empty
* `Access Level`: Might be needed to be set to `All` (e.g. if an external device will set/reset the value)

**Closed as completed** 2019-05-08 10:59 UTC
Labels: enhancement, question
